var day1 = prompt("Check Whether Its Holiday or not");
var sunday;
var saturday;
if(day1 == sunday){
console.log("ts holiday");
}else if(day1 ==saturday) {
console.log("its holiday");

}else{
console.log("its working day");
}




switch (day){
case 1:
console.log("sunday")
break;
case 2:
console.log("monday")
break;
case 3:
console.log("tuesday")
break;
case 4:
console.log("wednessdya")
break;
case 5:
console.log("thursday")
break;
case 6:
console.log("friday")
break;
case 7:
console.log("saturday")
break;
default:
    console.log("its not in weeks lists")
}

let day;

switch (){
    case 1:
}
const days = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];

let date = new Date();
 let day = date.day();
 let number = day.prompt("enter");

console.log(day);

switch(day){
    case 1 :
        alert("ITS HOLIDAY");
        break;
        case 7:
            alert("ITS HOLIDAY");
            break;
        default:
            alert("YOU NEED TO GO OFFICE");
            break;
}


let day ;
 switch(new Date().getDay()){
    case 0:
        day = "Sunday";
        break;
      case 1:
        day = "Monday";
        break;
      case 2:
        day = "Tuesday";
        break;
      case 3:
        day = "Wednesday";
        break;
      case 4:
        day = "Thursday";
        break;
      case 5:
        day = "Friday";
        break;
      case  6:
        day = "Saturday";
    }

 console.log(day);
 document.getElementById("day").innerHTML =day;


var names =["mahi","raju","shiva","vicky","kumar","king",];

for (let x =0 ; x < names.length;x++){
    console.log("MY NAME IS: "+names[x]  );


}

while(){

}
var output =0;
for (var i =1;i<=10;i++ ){
    output = output +i;
}
    console.log(output);


